pictures_folder: "pictures"
data_folder: "data"
templates_folder: "templates"
html_folder: "html"
html_pages_folder: "html_pages"
html_tables_folder: "html_tables"
figures_folder: "html_figures"
figures_suffix:
  impacts_table: "_impacts_table.html"
  impacts_table_new: "_impacts_table_new.html"
  impacts_table_ebkp: "_impacts_table_ebkp.png"
  ghg_ratio: "_ghg_ratio.png"
  ghg_ratio_ebkp: "_ghg_ratio_ebkp.png"
  material_sunburst: "_material_sunburst.html"
  material_sunburst_ebkp: "_material_sunburst_ebkp.html"
  co2_sunburst: "_co2_sunburst.html"
  reused_comp_bar: "_reused_comp_bar.html"
  sankey: "_sankey.html"
  imp_tot_lot_tonnes: "_impact_total_lot_tonnes.html"
  imp_tot_lot_kg_per_m2: "_impact_total_lot_kg_per_m2.html"
  imp_tot_lot_kg_per_m2_per_year: "_impact_total_lot_kg_per_m2_per_year.html"
  imp_tot_comparing_tonnes: "_impact_total_comparing_tonnes.html"
  imp_tot_comparing_kg_per_m2: "_impact_total_comparing_kg_per_m2.html"
  imp_tot_comparing_kg_per_m2_per_year: "_impact_total_comparing_kg_per_m2_per_year.html"
  imp_tot_bundle_tonnes: "_impact_total_bundle_tonnes.html"
  imp_tot_bundle_kg_per_m2: "_impact_total_bundle_kg_per_m2.html"
  imp_tot_bundle_kg_per_m2_per_year: "_impact_total_bundle_kg_per_m2_per_year.html"
html_suffix:
  building: "_building.html"
  case_study: "_case_study.html"
table_suffix:
  gwp_total: "_gwp_total.html"
  gwp_per_sqm: "_gwp_per_sqm.html"
  gwp_per_kg: "_gwp_per_kg.html"
photos_suffix: "-photo.jpg"
maps_suffix: "-map.png"
templates:
  building_template: "building_template.html"
  navigation_bar: "case_study_nav_bar.html"
  reuse_table: "reuse_table_template.html"
cases:
  Faraday: \\eistore2\igt-lesbat\RaD\107020_Reuse-LCA\3. Data+calculation\BL_Faraday\20221216_Faraday_Reuse_LCA_calculation_v10_graphes_MFD.xlsx
  Hobelwerk: \\eistore2\igt-lesbat\RaD\107020_Reuse-LCA\3. Data+calculation\ZH_Hobelwerk\ZH_Hobelwerk_Reuse_LCA_Calculation_v16 graphes.xlsx
  K118: \\eistore2\igt-lesbat\RaD\107020_Reuse-LCA\3. Data+calculation\ZH_K118\K118_Reuse_LCA_Calculation_v18.xlsx
  Elys : \\eistore2\igt-lesbat\RaD\107020_Reuse-LCA\3. Data+calculation\BS_Elys\2023_ELYS_Reuse_LCA_calculation_v9.xlsx
  Firmenich : \\eistore2\igt-lesbat\RaD\107020_Reuse-LCA\3. Data+calculation\GE_Firmenich\Reuse_LCA_Calculation_Firmenich_2023-v10.xlsx
  Denens : \\eistore2\igt-lesbat\RaD\123315_REMCO\3. Donnees+calculs\Denens - transformation grange\LCA_Calculation_DENENS_V6_MFD.xlsx

names:
  Faraday: Primeo Energie Kosmos
  Hobelwerk: Hobelwerk - Haus D
  K118: K 118
  Elys : Elys
  Firmenich : Firmenich
  Denens : Denens
photos:
  Faraday: pictures\\faraday-photo.png
  Hobelwerk: pictures\\Hobelwerk-photo.jpg
  K118: pictures\\K118-photo.jpg
  Elys : pictures\\Elys-photo.jpg
  Firmenich : pictures\\Firmenich-photo.jpg
  Denens : pictures\\Denens-photo.jpg

maps:
  Faraday: pictures\\Faraday-map.jpg
  Hobelwerk: pictures\\hobelwerk-map.png
  K118: pictures\\k118-map.png
  Elys : pictures\\Elys-map.png
  Firmenich : pictures\\Firmenich-map.png
  Denens : pictures\\Denens-map.jpg

lca_scopes:
  construction_domain: [A1-A3, A4, B4, C1-C4, Total]
  product_stage: [A1-A3]
  eol_stage: [C1-C4]
impact_categories: [GWP,UBP,PE-NR]
output_folder: "output"
excel_sheets:
